### ISSUE TITLE
Converting cheetah acquired data to kilosort format

### ISSUE THREAD

**Issue by ouardouzm** [ryanharvey1/ephys_tools#2]
Good Afternoon,
We were looking for a way to convert our Neuralynx .ncs electrophysiology data so we can use Kilosort. I tried your Ephys-tool.  When running handleAnimalMetaData.m I did not get animal id folder. and when I run ncs2dat.py I got the following 
>> ncs2dat
running 
Traceback (most recent call last): 
  File "C:\Users\ouard\OneDrive\Documents\MATLAB\ephys_tools\LFP\ncs2dat.py", line 108, in <module> 
    main() 
  File "C:\Users\ouard\OneDrive\Documents\MATLAB\ephys_tools\LFP\ncs2dat.py", line 45, in main 
    inputs = [open(input_name, 'rb') for input_name in input_names] 
  File "C:\Users\ouard\OneDrive\Documents\MATLAB\ephys_tools\LFP\ncs2dat.py", line 45, in <listcomp> 
    inputs = [open(input_name, 'rb') for input_name in input_names] 
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ouard\\OneDrive\\Desktop\\mouse' 
ERROR ERROR ERROR ERROR

Do you have an updated version that I can use for my analysis of course you will be sited in any publication. 

Thanks you for the tools

Best Regards

Mohamed Ouardouz

**Comment by ryanharvey1** [comment]
1. It looks like you might be running ```ncs2dat.py``` instead of ```ncs2dat.m```. In matlab, cd to your session folder that contains the .ncs files and try running ncs2dat. 

2. As for ```handleAnimalMetaData.m```, ```create_project_folder.m``` from step 5 in the readme will create all the subfolders necessary to use the toolbox.  

Let me know if these solutions work out for you.

**Comment by ouardouzm** [comment]
Can you elaborate on how to populate the newly created folder It may be the problem.
thanks

**Comment by ryanharvey1** [comment]
```ncs2dat.m``` does not depend on any specific folder structure. It just needs to be run when you are in a folder with .ncs files. It will generate and save your .dat file for use in kilosort to that same folder.

**Comment by ouardouzm** [comment]
Thanks for your help and for sharing the ephys-tools. it did work 
All the best
