### ISSUE TITLE
postprocess

### ISSUE THREAD

**Issue by ouardouzm** [ryanharvey1/ephys_tools#4]
Your recent paper show excellent results. I am recording from PFC in a model of epilepsy and I would like to use ephys_tools for my analysis. here is one of the Error I got with postprocess  

>> postprocess
Error: File: load_spikes.m Line: 40 Column: 23
Invalid syntax for calling function 'means' on the path. Use a valid
syntax or explicitly initialize 'means' to make it a variable.

Error in postprocess (line 28)
[S,avgwave,ID,cellnum,tetrode,clusterquality] = load_spikes(path);

Thanks for your help

**Comment by lolaBerkowitz** [comment]
It seems you don't have the average waveforms. Did you run after_spikesort_cleanup on your spike sorted data? You'll need the output of that in the 'Sorted' folder for postprocess to work. Right now, our pipeline accommodates kilosort2/phy, Spike Sort 3D, or MClust for spike sorting.

**Comment by ouardouzm** [comment]
I did run it. I have some .mat files in the sorted TT1_info.mat and TT1.mat for the 4 tetrodes. I did run again the postprocess and I got the same Error. Could you please sent me a more detailed procedure of using ephys_tools to ouardouz12@gmail.com. 
I used kilosort2 and phy2. in this case I used Ks2wrapper.m as suggested.
Thanks for your help.

**Comment by ryanharvey1** [comment]
I'm not sure what would have caused your error without more information. Try opening TT1_info.mat to see if the variable "means" exists. That variable should be a cell array of your average waveforms.
